#!/usr/bin/env bash
# -----------------------------------------------------------------
# Script   : xp_autoinstall
# Descrição: Auto instalação de temas
# Versão   : 0.1
# Autor    : Jesher Minelli <jesherdevsk8@gmail.com>
# Data     : sáb 25 jun 2022
# Licença  : GNU/GPL v3.0
# -----------------------------------------------------------------
# Uso: ./xp_autoinstall
# -----------------------------------------------------------------

#-------------------------- VARIAVEIS -----------------------------

pacotes=( wget git )
dir_themes_icons=( "$HOME/.themes" "$HOME/.icons" )
dir_downloads="$HOME/Downloads"
dir_imagens="$HOME/Imagens"
# abaixo deixei como array, caso eu precise baixar mais de uma imagem
download_wget=( "https://archive.org/download/bliss-600dpi/bliss-600dpi.png" )
clone_theme="https://github.com/B00merang-Project/Windows-XP.git $dir_downloads/Windows-XP-Themes"
clone_icon="https://github.com/B00merang-Artwork/Windows-XP.git $dir_downloads/Windows-XP-Icons"
themes="$dir_downloads/Windows-XP-Themes"
icons="$dir_downloads/Windows-XP-Icons"

#--------------------------- TESTES -------------------------------

[[ $UID = '0' ]] && echo "Root Não...!" && exit 1

# Se os diretórios existem, nada acontece (no error if existing) #
mkdir -p "$themes" "$icons" "$dir_downloads" "$dir_imagens"

for dirs in "${dir_themes_icons[@]}"; do
	mkdir -p "$dirs"
done

#--------------------------- FUNÇÕES ------------------------------

function instalar_dependencias(){
	for programas in "${pacotes[@]}"; do
		if [[ ! -x $(which "$programas") ]]; then
			echo "[INFO] $programas Não está instalado. Instalando......."
			sudo apt install "$programas" -y 1> /dev/null 2>&1
		fi			
	done
}

function baixar_imagens(){
	local arquivo=$(cut -d / -f 6 <<< "$download_wget")
	if [[ ! -f "$dir_imagens/$arquivo" ]]; then
		wget "$download_wget" -P "$dir_imagens"
	fi
}

function clona_repo() {
	git clone $clone_icon
	git clone $clone_theme
}

function copiar_clones(){
	cp -r "$themes/Windows XP Luna" "$HOME/.themes"
	cp -r "$icons" "$HOME/.icons"
}

#---------------------------- MAIN --------------------------------

instalar_dependencias
baixar_imagens
clona_repo
copiar_clones